# Configure enabled oh-my-zsh plugins here
ZSH=$HOME/.zshit/oh-my-zsh/
export TERM=xterm-256color # It only works with 256 capable terminals, sorry =)
export PATH=$HOME/.bin/:$HOME/.cw/def:$HOME/.perl5/bin:$PATH
plugins=(git zsh-syntax-highlighting-filetypes zsh-syntax-highlighting )
source ~/.zshit/confs/enable_powerline
source ~/.zshit/oh-my-zsh/oh-my-zsh.sh
eval $( dircolors -b ~/.zshit/LS_COLORS/LS_COLORS )
alias ls=ls++
