# Configure enabled oh-my-zsh plugins here
ZSH=$HOME/.prettierTerminal/zsh/oh-my-zsh/
export TERM=xterm-256color # It only works with 256 capable terminals, sorry =)
export PATH=$HOME/.bin/:$HOME/.perl5/bin:$PATH:~/.local/bin

plugins=(git zsh-syntax-highlighting-filetypes zsh-syntax-highlighting )

source ~/.prettierTerminal/zsh/oh-my-zsh/oh-my-zsh.sh
source ~/.prettierTerminal/zsh/confs/enable_powerline

eval $( dircolors -b ~/.prettierTerminal/zsh/LS_COLORS/LS_COLORS )
