config:
	@echo "Nope yet"

experimental:
	@bash get_xresources_solarized.sh
	@mkdir -p ~/.config/mc
	@cat src/mc-solarized-skin/solarized.ini >> ~/.config/mc/ini
	@cp src/irssi-colors-solarized/solarized-universal.theme ~/.irssi/
	@cp src/mutt-colors-solarized/mutt-colors-solarized-light-256.muttrc ~/.mutt/
	@echo "Now source ~/mutt-colors-solarized-light-256.muttr on your .muttrc"
