zinit for \
    light-mode zsh-users/zsh-autosuggestions \
    light-mode zdharma/fast-syntax-highlighting \
    light-mode desyncr/auto-ls \
    light-mode MichaelAquilina/zsh-auto-notify

zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure

zinit ice src"shell/key-bindings.zsh"
zinit light junegunn/fzf

zinit ice from"gh-r" as"program" mv"*/bat bat"
zinit light sharkdp/bat

zinit ice from"gh-r" as"program" 
zinit load junegunn/fzf-bin

zinit ice atclone"dircolors -b LS_COLORS > c.zsh" atpull'%atclone' pick"c.zsh" nocompile'!'
zinit light trapd00r/LS_COLORS


setopt appendhistory
HISTFILE=~/.zhistory
HISTSIZE=1000
SAVEHIST=1000

export PATH="$PATH:~/.local/bin:~/.poetry/bin:$PATH"
export EDITOR=nvim

export AUTO_LS_NEWLINE=false
export AUTO_LS_COMMANDS=("ls")
export ENHANCD_DOT_SHOW_FULLPATH=1

# Force some default command replacements.
alias cat=bat --paging=never
alias tree="lsd --tree"
ls() { lsd $@; }
alias vim=nvim

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

[[ -e ~/.zshrc.custom ]] && source ~/.zshrc.custom
