all:config

config:
	@install -d ~/.prettierTerminal/tmux
	@cp -r src/* ~/.prettierTerminal/tmux
	@echo "Now just put 'source-file ~/.prettierTerminal/tmux/confs/tmux.conf' on your .tmux.conf"
	@bash ./install-powerline

